# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: <img src="/media/cropped-cropped-fccanWebLogo-300x123.png">
title_short: FCCAN
email: info@fccan.org
description: >- # this means to ignore newlines until "baseurl:"
  FCCAN’s mission is to create community based on furthering economic, 
  social, and environmental justice, sustainability, human rights, and 
  peace for all by building coalitions, developing strategies and 
  actions, and supporting existing progressive organizations.
url: "https://fccan.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FCCAN2
mast-background: media/IMG_2882.jpeg

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  homepage-sections:
    output: false
    permalink: /:collection
  staff:
    output: false
    permalink: /:collection
  events:
    output: false
    permalink: /:collection
  resources:
    output: false
    permalink: /:collection
  spokescouncil:
    output: false
    permalink: /:collection
  values:
    output: false
    permalink: /:collection
  affiliates:
    output: true
    permalink: /:collection/:title
  affiliates-es:
    output: true
    permalink: /es/affiliates/:title
  programs:
    output: true
    permalink: /:collection/:title
  programs-es:
    output: true
    permalink: /es/programs/:title
  blog:
    output: true
    permalink: /:collection/:title
  blog-es:
    output: true
    permalink: /es/blog/:title


social:
  name: FCCAN
  links:
    - https://twitter.com/FCCAN2

css_inline: true
