backend:
  name: git-gateway
  branch: master

local_backend:
  url: http://localhost:8076/api/v1

media_folder: "media"
public_folder: "/media"

collections:
  - label: "Homepage Sections"
    name: "homepage-sections"
    folder: "_homepage-sections"
    slug: "{{name}}"
    summary: "{{name}} -- {{id}} -- {{order}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Section ID", name: "id", widget: "string", default: "give-me-an-id-" }
      - { label: "Section Name", name: "name", widget: "string" }
      - { label: "Section order", name: "order", widget: "number",  default: 50, valueType: "int", min: 1, max: 101 }
      - { label: "Section Title (English)", name: "title-en", widget: "string" }
      - { label: "Section Body (English)", name: "body-en", widget: "markdown" }
      - { label: "Section Title (Spanish)", name: "title-es", widget: "string" }
      - { label: "Section Body (Spanish)", name: "body-es", widget: "markdown" }
  - label: "Programs English"
    name: "programs-en"
    folder: "_programs"
    slug: "{{title}}"
    summary: "{{title}}"
    create: true
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - label: "Files"
        name: "files"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - { label: "Title (English)", name: "title", widget: "string" }
      - { label: "Body (English)", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "programs"}
      - { label: "Lang", name: "lang", widget: "hidden", default: "en"}
      - { label: "Ordering", name: "ordering", widget: "select", options: ["important", "first", "neutral", "last"],default: ["neutral"] }
      - { label: "Associated Group", name: "associated-group", widget: "relation", collection: "groupings", search_fields: ["group"], value_field: "group", multiple: true }
  - label: "Programs Spanish"
    name: "programs-es"
    folder: "_programs-es"
    slug: "{{en-program}}"
    summary: "{{en-program}}"
    create: true
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - label: "Files"
        name: "files"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - { label: "Title (Spanish)", name: "title", widget: "string" }
      - { label: "Body (Spanish)", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "programs"}
      - { label: "Lang", name: "lang", widget: "hidden", default: "es"}
      - { label: "Ordering", name: "ordering", widget: "select", options: ["important", "first", "neutral", "last"],default: ["neutral"] }
      - { label: "Program in English", name: "en-program", widget: "relation", collection: "programs-en", search_fields: ["title"], value_field: "title"}
      - { label: "Associated Group", name: "associated-group", widget: "relation", collection: "groupings", search_fields: ["group"], value_field: "group", multiple: true }
  - label: "Values"
    name: "values"
    folder: "_values"
    slug: "{{title-en}}"
    summary: "{{title-en}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Name (English)", name: "title", widget: "string" }
      - { label: "Info (English)", name: "body", widget: "markdown" }
      - { label: "Name (Spanish)", name: "title-es", widget: "string" }
      - { label: "Info (Spanish)", name: "body-es", widget: "markdown" }
      - { label: "Ordering", name: "ordering", widget: "select", options: ["important", "first", "neutral", "last"],default: ["neutral"] }
  - label: "Affiliates"
    name: "affiliates-en"
    folder: "_affiliates"
    slug: "{{title}}"
    summary: "{{title}}"
    create: true
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - { label: "Org Name (English)", name: "title", widget: "string" }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'affiliates' }
      - { label: "Associated Group", name: "associated-group", widget: "relation", collection: "groupings", search_fields: ["group"], value_field: "group", multiple: true }
      - { label: "About (English)", name: "body", widget: "markdown" }
  - label: "Affiliates Spanish"
    name: "affiliates-es"
    folder: "_affiliates-es"
    slug: "{{en-affiliate}}"
    summary: "{{en-affiliate}}"
    create: true
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - { label: "Org Name (Spanish)", name: "title", widget: "string" }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'affiliates' }
      - { label: "About (Spanish)", name: "body", widget: "markdown" }
      - { label: "Associated Group", name: "associated-group", widget: "relation", collection: "groupings", search_fields: ["group"], value_field: "group", multiple: true }
      - { label: "Affiliate in English", name: "en-affiliate", widget: "relation", collection: "affiliates-en", search_fields: ["title"], value_field: "title"}
  - label: "Resources"
    name: "resources"
    folder: "_resources"
    slug: "{{title-en}}"
    summary: "{{title-en}}"
    create: true
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - label: "Files (English)"
        name: "files-en"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - label: "Files (Spanish)"
        name: "files-es"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - label: "Files (Additional)"
        name: "files-etc"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - { label: "Title (English)", name: "title-en", widget: "string" }
      - { label: "Body (English)", name: "body-en", widget: "markdown", required: false }
      - { label: "Title (Spanish)", name: "title-es", widget: "string" }
      - { label: "Body (Spanish)", name: "body-es", widget: "markdown", required: false }
      - { label: "Associated Group", name: "associated-group", widget: "relation", collection: "groupings", search_fields: ["group"], value_field: "group", multiple: true }
      - { label: "Ordering", name: "ordering", widget: "select", options: ["important", "first", "neutral", "last"],default: ["neutral"] }
  - label: "Groupings"
    name: "groupings"
    folder: "_groupings"
    slug: "{{group}}"
    summary: "{{group}}"
    create: true
    identifier_field: 'group'
    editor:
      preview: false
    fields:
      - { label: "Group Name", name: "group", widget: "string" }
  - label: "Blog English"
    name: "blog-en"
    folder: "_blog"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    summary: "{{year}}-{{month}}-{{day}}-{{title}}"
    create: true
    identifier_field: "title"
    sortable_fields: ['date']
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: "Title (English)", name: "title", widget: "string" }
      - { label: "Body (English)", name: "body", widget: "markdown", required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Associated Group", name: "associated-group", widget: "relation", collection: "groupings", search_fields: ["group"], value_field: "group", multiple: true }
  - label: "Blog Spanish"
    name: "blog-es"
    folder: "_blog-es"
    slug: "{{year}}-{{month}}-{{day}}-{{blog-en}}"
    summary: "{{year}}-{{month}}-{{day}}-{{blog-en}}"
    create: true
    identifier_field: "title"
    sortable_fields: ['date']
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: "Title (English)", name: "title", widget: "string" }
      - { label: "Body (English)", name: "body", widget: "markdown", required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Associated Group", name: "associated-group", widget: "relation", collection: "groupings", search_fields: ["group"], value_field: "group", multiple: true }
      - { label: "Blog in English", name: "blog-en", widget: "relation", collection: "blog-en", search_fields: ["title"], value_field: "title"}
  - label: "Staff Members"
    name: "staff"
    folder: "_staff"
    slug: "{{name}}"
    summary: "{{name}}"
    create: true
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - { label: "Name", name: "name", widget: "string", default: "", }
      - { label: "Email", name: "email", widget: "string", default: "", required: false }
      - { label: "Job Title (English)", name: "title-en", widget: "string", default: "", }
      - { label: "Job Title (Spanish)", name: "title-es", widget: "string", default: "", }
      - { label: "About You (English)", name: "body-en", widget: "markdown", required: false }
      - { label: "About You (Spanish)", name: "body-es", widget: "markdown", required: false }
      - { label: "Ordering", name: "ordering", widget: "select", options: ["important", "first", "neutral", "last"],default: ["neutral"] }
  - label: "Spokescouncil"
    name: "spokescouncil"
    folder: "_spokescouncil"
    slug: "{{name}}"
    summary: "{{name}}"
    create: true
    editor:
      preview: false
    fields:
      - label: "Picture"
        name: "picture"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - { label: "Name", name: "name", widget: "string", default: "", }
      - { label: "About You (English)", name: "body-en", widget: "markdown" }
      - { label: "About You (Spanish)", name: "body-es", widget: "markdown" }
      - { label: "Ordering", name: "ordering", widget: "select", options: ["important", "first", "neutral", "last"],default: ["neutral"] }
